// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:adf_demo/features/home/data/dto/banner_dto.dart';
import 'package:adf_demo/features/home/data/dto/cached_banners_envelope.dart';
import 'package:adf_demo/features/home/data/dto/cached_movies_envelope.dart';
import 'package:adf_demo/features/home/data/dto/movie_dto.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BannerDtoAdapter());
    registerAdapter(CachedBannersEnvelopeAdapter());
    registerAdapter(CachedMoviesEnvelopeAdapter());
    registerAdapter(MovieDtoAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BannerDtoAdapter());
    registerAdapter(CachedBannersEnvelopeAdapter());
    registerAdapter(CachedMoviesEnvelopeAdapter());
    registerAdapter(MovieDtoAdapter());
  }
}
